apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  MPT_DJANGO_SECRET_KEY: {{ .Values.global.DjangoSecretKey }}
  MPT_API_TOKEN: {{ .Values.global.MpApiToken }}
  EXT_WEBHOOKS_SECRETS: {{ .Values.global.WebhookSecretKeys }}
  EXT_AIRTABLE_API_TOKEN: {{ .Values.global.AirTableApiToken }}
  EXT_MSTEAMS_WEBHOOK_URL: {{ .Values.global.MsTeamsWebhookUrl }}
  EXT_CRM_CLIENT_SECRET: {{ .Values.global.CrmClientSecret }}
  EXT_FFC_OPERATIONS_SECRET: {{ .Values.global.FfcOperationsSecret }}
  EXT_AZURE_STORAGE_CONNECTION_STRING: {{ .Values.global.AzureStorageConnectionString}}
