{{- range $name, $config := .Values.global.cronjobs }}
apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: {{ $.Release.Namespace }}
  name: {{ include "common.fullname" $ }}-cronjob-{{ $name }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
spec:
  schedule: "{{ $config.schedule }}"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  startingDeadlineSeconds: 3600
  suspend: false
  jobTemplate:
    spec:
      parallelism: 1
      completions: 1
      backoffLimit: 3
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          volumes:
            - name: pyra-keyvault-certificate
              secret:
                secretName: ops-pyc-cluster-teamsetup-pyra-keyvault-certificate
          containers:
            - name: {{ $name }}
              securityContext:
                {{- toYaml $.Values.securityContext | nindent 16 }}
              image: "{{ $.Values.global.repositoryUrl }}{{ $.Values.image.repository }}:{{ $.Chart.AppVersion }}"
              command:
                - swoext
              args:
                - django
                - {{ $config.command }}
              env:
                - name: "AZURE_CLIENT_CERTIFICATE_PASSWORD"
                  valueFrom:
                    secretKeyRef:
                      name: ops-pyc-cluster-teamsetup-pyra-keyvault-certificate
                      key: keyvault-certificate-password
                # Map shared config map keys to environment variables
                - name: MPT_KEY_VAULT_NAME
                  valueFrom:
                    configMapKeyRef:
                      name: ops-pyc-cluster-teamsetup-default-env-variables
                      key: PYRA_PYRA__KEYVAULT__SOURCES__0__URI
                - name: AZURE_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: ops-pyc-cluster-teamsetup-pyra-xcluster-credentials
                      key: PYRA_PYRA__AZUREAD__AUTHENTICATION__APPLICATIONID
                - name: AZURE_CLIENT_CERTIFICATE_PATH
                  valueFrom:
                    secretKeyRef:
                      name: ops-pyc-cluster-teamsetup-pyra-xcluster-credentials
                      key: PYRA_PYRA__AZUREAD__AUTHENTICATION__CERTIFICATEPATH
                - name: AZURE_TENANT_ID
                  value: {{ $.Values.global.azure_tenant_id }}
              volumeMounts:
                - name: pyra-keyvault-certificate
                  mountPath: "/app/pyra-keyvault-certificate"
                  readOnly: true
              imagePullPolicy: {{ $.Values.image.pullPolicy }}
              envFrom:
                - configMapRef:
                    name: ops-pyc-cluster-teamsetup-default-env-variables
                - secretRef:
                    name: ops-pyc-cluster-teamsetup-pyra-xcluster-credentials
                - configMapRef:
                    name: {{ include "common.fullname" $ }}
                - secretRef:
                    name: {{ include "common.fullname" $ }}
          restartPolicy: Never
          terminationGracePeriodSeconds: 30
---
{{- end }}
