{{- range $name, $config := .Values.global.cronjobs }}
apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: {{ $.Release.Namespace }}
  name: {{ include "common.fullname" $ }}-cronjob-{{ $name }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
spec:
  schedule: "{{ $config.schedule }}"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  startingDeadlineSeconds: 3600
  suspend: false
  jobTemplate:
    spec:
      parallelism: 1
      completions: 1
      backoffLimit: 3
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
          labels:
            azure.workload.identity/use: "true"
        spec:
          serviceAccountName: swo-extension-aws-sa
          containers:
            - name: {{ $name }}
              securityContext:
                {{- toYaml $.Values.securityContext | nindent 16 }}
              image: "{{ $.Values.global.registryUrl }}{{ $.Values.image.repository }}:{{ $.Chart.AppVersion }}"
              command:
                - swoext
              args:
                - django
                - {{ $config.command }}
              imagePullPolicy: {{ $.Values.image.pullPolicy }}
              envFrom:
                - configMapRef:
                    name: {{ include "common.fullname" $ }}
                - secretRef:
                    name: {{ include "common.fullname" $ }}
          restartPolicy: Never
          terminationGracePeriodSeconds: 30
---
{{- end }}
