global:
  OTELServiceName: Swo.Extensions.AWS
  AppInsightsConnectionString: ZGVmYXVsdA==
  ServiceName: default
  MpPortalBaseUrl: default
  MpBaseUrl: default
  MpApiToken: ZGVmYXVsdA==
  ConfigJson: ZGVmYXVsdA==
  DjangoSecretKey: ZGVmYXVsdA==
  MpProductsIds: default
  WebhookSecretKeys: ZGVmYXVsdA==
  AirTableApiToken: ZGVmYXVsdA==
  AirTablePoolBase: '{}'
  AirTableNotificationPoolBase: '{}'
  MsTeamsWebhookUrl: ZGVmYXVsdA==
  EmailNotificationsSender: default
  EmailNotificationsEnabled: "1"
  CrmOAuthUrl: default
  CrmClientId: default
  CrmClientSecret: ZGVmYXVsdA==
  CrmAudience: default
  CcpOauthUrl: default
  CcpClientId: default
  CcpOauthScope: default
  CcpOauthCredentialsScope: default
  CcpApiBaseUrl: default
  MpSetupContextsFunc: swo_aws_extension.flows.fulfillment.base.setup_contexts
  MpOrdersApiPollingIntervalSecs: 60
  CrmApiBaseUrl: default
  AwsOpenIdScope: default
  AwsRegion: us-east-1
  AirTableBase: default
  CcpKeyVaultSecretName: default
  ExtMinimumMpaThreshold: 1
  FfcOperationsSecret: ZGVmYXVsdA==
  FfcOperationsApiBase: default
  FfcOperationsSub: default
  MpNotifyCategories: "{}"

  replicaCountAPI: 1
  replicaCountWorker: 1
  repositoryUrl: ""
  azure_tenant_id: ""

  cronjobs:
    aws-invitations:
      schedule: ""
      command: order_process_aws_invitations
    sync-agreements:
      schedule: ""
      command: synchronize_agreements
    check-pool:
      schedule: ""
      command: check_pool_accounts_notifications
    ccp-secret:
      schedule: ""
      command: refresh_ccp_openid_secret
    generate-billing:
      schedule: ""
      command: generate_billing_journals




